# Generated by Django 4.2.15 on 2024-08-21 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_name_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='market_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_class', models.CharField(blank=True, max_length=255, null=True)),
                ('product_data', models.JSONField(blank=True, default=list, null=True)),
                ('as_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
