# Generated by Django 5.1.3 on 2024-12-19 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_market_data_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_opening_Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='fx_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closingrate', models.CharField(blank=True, max_length=255, null=True)),
                ('as_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='pep_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pep_data', models.JSONField(blank=True, default=list, null=True)),
                ('as_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
